language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get install -y liblapack-dev clang-6.0 build-essential cmake
                            libarmadillo-dev libboost-all-dev libopenmpi-dev
                            python3-numpy
after_success:
notifications:
  email: true
stages:
  - Compile
  - Tests

jobs:
  include:
  - stage: "Compile"
    name: "Compile Serial"
    script: cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make -j 4
  - script: ./install-mpi-travis.sh 
    name : "Install MPI"
  - stage: "Tests"
    name: "Unit Tests"
    script: cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make -j 4 && make test
  - script: ./install-mpi-travis.sh && cd $TRAVIS_BUILD_DIR && travis_wait 65 python3 test/integration_test.py -v
    name: "Integration Tests"