---
matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # works on Trusty
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y liblapack-dev cmake
                            libarmadillo-dev libboost-all-dev libopenmpi-dev
                            python3-numpy tree libsnappy-dev
stages:
  - compile clang

jobs:
  include:
    - stage: "compile clang"
      name: "compile serial"
      script: cd $TRAVIS_BUILD_DIR && mkdir build && cd build &&
              cmake -DCLANG_BUILD=ON .. && make -j 4 && make test
