---
language: cpp
sudo: required
dist: xenial
compiler:
  - gcc

os:
  - linux
  - osx

before_install:
  - ./.travis/before_install.sh


install: 
  - ./.travis/install.sh
  - ./.travis/install_mpi.sh
