language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get install -y liblapack-dev clang-6.0 build-essential cmake
                            libarmadillo-dev libboost-all-dev libopenmpi-dev
                            python3-numpy
script:
  - cd $TRAVIS_BUILD_DIR && mkdir build_mpi && cd build_mpi && cmake -DMPI_BUILD=ON .. && make install
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make
after_success:
notifications:
  email: true


jobs:
  include:
  - stage: "Tests"
    name: "Unit Tests"
    script: cd $TRAVIS_BUILD_DIR && cd build && make test
  - script: cd $TRAVIS_BUILD_DIR && travis_wait python3 test/integration_test.py -v
    name: "Integration Tests"