name: C++ Build and Test (CI)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install-deps
        run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential liblapack-dev cmake libboost-all-dev libarmadillo-dev libsnappy-dev
      - name: build
        run: rm -rf build ; mkdir build && cd build && cmake -DBUILD_TESTS=ON .. && make
      - name: test
        run: make test
